export default function SummaryCard({ summary, aiGenerated, autoNote }) {
  if (!summary) return null;

  return (
    <div className="bg-pastel-yellow border-2 border-yellow-200 rounded-2xl p-4 md:p-5">
      <p className="font-extrabold text-yellow-800 mb-1 flex items-center gap-2">
        <span>📝</span> This Week's Summary
      </p>
      <p className="text-yellow-900 leading-relaxed">{summary}</p>
      {aiGenerated && (
        <p className="text-xs text-yellow-700 mt-2 font-semibold">✨ Summary generated by AI</p>
      )}
      {autoNote && (
        <p className="text-xs text-yellow-700 mt-2 font-semibold">✨ Summary generated automatically (AI unavailable)</p>
      )}
    </div>
  );
}
